# Generated by Django 4.1.2 on 2022-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='nickName',
        ),
        migrations.AlterField(
            model_name='user',
            name='addTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='openId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
