# Generated by Django 4.1.2 on 2022-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0002_rename_nickname_user_nickname_alter_user_addtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headPortrait',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
