# Generated by Django 4.1.2 on 2022-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0004_alter_user_headportrait_alter_user_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
