# Generated by Django 4.1.2 on 2022-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0005_alter_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lover',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='praise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='headPortrait',
            field=models.CharField(default='static/heard.png', max_length=255),
        ),
    ]
