# Generated by Django 4.1.2 on 2022-10-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0006_user_lover_user_praise_alter_user_headportrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lover',
        ),
    ]
