# Generated by Django 4.1.2 on 2022-10-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0008_alter_diary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='addTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='addTime',
            field=models.DateTimeField(null=True),
        ),
    ]
