# Generated by Django 4.1.2 on 2022-10-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidiary', '0010_remove_video_diary_diary_image_diary_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='updateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
